[pytest]
testpaths = tests
python_files = test_*.py
pythonpath = .
addopts = -v 
markers =
    power: Power cycle tests
    power_on: Power ON test
    power_off: Power OFF test
    device_enumeration: Device Enumeration test