name: copy json and start running 

on:
  push: 

jobs:
  run-pytest:
    runs-on: [self-hosted, runner_1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: exploring the device_data.json local path
        shell: cmd
        run: echo %GITHUB_WORKSPACE%

      - name: Copy device_data.json to local folder
        shell: cmd
        run: |
          copy "%GITHUB_WORKSPACE%\device_data.json" "C:\Users\nd\Desktop\Pytest\data\device_data.json"

      - name: Run Pytest
        shell: cmd
        run: |
          cd C:\Users\nd\Desktop\Pytest
          pytest tests/test_powercycle.py