name: Run Pytest Automation

on:
  push:
    branches:
      - main

jobs:
  run-tests:

    runs-on: [self-hosted, runner_2]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner workspace
        shell: cmd
        run: |
          echo Current workspace location:
          echo %GITHUB_WORKSPACE%
          dir

      - name: Run pytest
        shell: cmd
        run: |
          pytest tests/test_powercycle.py  --html=report.html --self-contained-html

