name: Run Pytest Automation

on:
  push:
    branches:
      - main

jobs:
  run-tests:

    runs-on: [self-hosted, runner_7]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner workspace
        shell: cmd
        run: |
          echo Current workspace location:
          echo %GITHUB_WORKSPACE%
          dir

      - name: Run pytest
        shell: cmd
        run: |
          python utils/update_device_data.py

      - name: Run pytest and save report
        shell: cmd
        run: |
          set mydate=%date:~-4%-%date:~4,2%-%date:~7,2%
          set filename=report_%RUNNER_NAME%_%mydate%.html
          echo %filename%

          if not exist C:\Users\Testing\Documents\runner_reports\Sunday_report mkdir C:\Users\Testing\Documents\runner_reports\Sunday_report

          pytest tests/test_silence_detection.py --html=C:\Users\Testing\Documents\runner_reports\Sunday_report\%filename% --self-contained-html








