name: Run Pytest Automation

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner info
        shell: cmd
        run: |
          echo Runner Name: %RUNNER_NAME%
          echo DEVICE_KEY: %DEVICE_KEY%

      - name: Update JSON based on runner
        shell: cmd
        run: |
          python utils/update_device_data.py

      - name: Run pytest
        shell: cmd
        run: |
          pytest tests/test_silence_detection.py -v -s 

          

